### ISSUE TITLE
Weird scrolling

### ISSUE THREAD

**Issue by glancashire** [Zacharysp/CalendarHeatmap#7]
Hi Zachary

Thank you for your quick turnaround, just tell me if I ask too much.

There is a slight scrolling problem, which I cannot explain. See screenshots.

On initial load the heat map scrolls such, that the first date is not visible. 
![calendarheatmap_onload](https://user-images.githubusercontent.com/314516/79432193-c8ab9c80-7fcb-11ea-8cce-83459a4b39c8.png)

Even though there is enough space to display the first date when scrolling manually.
![calendarheatmap_scroll](https://user-images.githubusercontent.com/314516/79432202-cc3f2380-7fcb-11ea-8ce6-ac13a7ce0ccc.png)

A simple solution would be to allow configuration if the heatmap should be scrolled to the beginning or end on load.

Cheers, Graham

**Comment by Zacharysp** [comment]
Hi Graham,

There is no such thing about asking too much, questions are always welcome.

The issue here is I added a scroll to end right after building the calendar per my personal project requirement.

And now, it's better to remove the scrolling, and public the scroll function. Then, you can scroll the collection view as you needed.

I will work on that soon.

**Comment by glancashire** [comment]
That would be great
